steps:
- id: 'Build docker image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/converter-image', 'converter-image' ]
- id: 'Push image to repository'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/converter-image']
- id: 'Deploy convert-spreadshirt to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'convert-spreadshirt', '--concurrency=1', '--memory=2Gi', '--max-instances=10', '--platform=managed', '--region=us-central1', '--image=gcr.io/$PROJECT_ID/converter-image', '--set-env-vars=CONVERTED_BUCKET_NAME=design-transformer-output,TYPE=spreadshirt']
- id: 'Deploy convert-amazon-merch to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'run', 'deploy', 'convert-amazon-merch', '--concurrency=1', '--memory=2Gi', '--max-instances=10', '--platform=managed', '--region=us-central1', '--image=gcr.io/$PROJECT_ID/converter-image', '--set-env-vars=CONVERTED_BUCKET_NAME=design-transformer-output,TYPE=amazon']
images:
- 'gcr.io/$PROJECT_ID/converter-image'